EncryptionConfig:
  Enabled: false
  Type: aes
  TimeConsideration: 1
  Threads: 2
CompressionConfig:
  Enabled: false
  Type: gzip
PoolConfig:
  URI: amqp://guest:19920802@127.0.0.1:5672/guest-vhost
  ApplicationName: TurboCookedRabbit
  SleepOnErrorInterval: 100
  MaxCacheChannelCount: 50
  MaxConnectionCount: 10
  Heartbeat: 6
  ConnectionTimeout: 10
  TLSConfig:
    EnableTLS: false
    PEMCertLocation: test/catest.pem
    LocalCertLocation: client/cert.ca
    CertServerName: hostname-in-cert
ConsumerConfigs:
  RabbitConsumerOne:
    Enabled: true
    QueueName: guest-queue
    ConsumerName: RabbitConsumerOne
    SleepOnErrorInterval: 5
    SleepOnIdleInterval: 0
    AutoAck: false
    Exclusive: false
    NoWait: false
    QosCountOverride: 100
PublisherConfig:
  AutoAck: false
  SleepOnIdleInterval: 0
  SleepOnErrorInterval: 0
  PublishTimeOutInterval: 500
  MaxRetryCount: 5